{% set name = "archive-path" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83ec72129a9558b0471a62f600e10116b09fc410ab7f17cf05d05665189026e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - flit >2,<4
  run:
    - python >=3.8

test:
  imports:
    - archive_path

about:
  home: https://github.com/aiidateam/archive-path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A package to provide pathlib like access to zip & tar archives.

extra:
  recipe-maintainers:
    - chrisjsewell
