{% set name = "archive-path" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be1891ffb0f03dc6efd4c812f7635251a45ccae647d684adacdb813afa6d5ae9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit >2,<4
  run:
    - python >=3.6

test:
  imports:
    - archive_path

about:
  home: https://github.com/aiidateam/archive-path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A package to provide pathlib like access to zip & tar archives.

extra:
  recipe-maintainers:
    - chrisjsewell
